(setq arr (alloc 5))
(setq n 5)

(setq i 0)
(while (< i n)
  (if (= i 0) (aset arr 0 42)
    (if (= i 1) (aset arr 1 3)
      (if (= i 2) (aset arr 2 7)
        (if (= i 3) (aset arr 3 19)
          (aset arr 4 1)))))
  (setq i (+ i 1))
)

(setq i 0)
(while (< i n)
  (setq j 0)
  (while (< j (- n i 1))
    (setq x (aget arr j))
    (setq y (aget arr (+ j 1)))
    (if (> x y)
      (progn
        (aset arr j y)
        (aset arr (+ j 1) x)
      )
    )
    (setq j (+ j 1))
  )
  (setq i (+ i 1))
)

(setq k 0)
(while (< k n)
  (setq v (aget arr k))
  (print v)
  (if (< (+ k 1) n) (print " "))
  (setq k (+ k 1))
)
(print "\n")
