(setq n 0)
    (setq val 0)
    (setq building 0)

    (setq ch (read))
    (while (!= ch 0)
      (if (= ch 10)
        (while (= building 1)
          (if (= n 0) (setq a0 val)
            (if (= n 1) (setq a1 val)
              (if (= n 2) (setq a2 val)
                (if (= n 3) (setq a3 val)
                  (setq a4 val)))))
          (setq n (+ n 1))
          (setq building 0)
          (setq ch 0)
        )
        (if (= ch 32)
          (while (= building 1)
            (if (= n 0) (setq a0 val)
              (if (= n 1) (setq a1 val)
                (if (= n 2) (setq a2 val)
                  (if (= n 3) (setq a3 val)
                    (setq a4 val)))))
            (setq n (+ n 1))
            (setq val 0)
            (setq building 0)
          )
          (progn
            (setq val (+ (* val 10) (- ch 48)))
            (setq building 1)
          )
        )
      )
      (if (!= ch 0) (setq ch (read)))
    )

    (setq i 0)
    (while (< i n)
      (setq j 0)
      (while (< j (- n i 1))
        (setq x (if (= j 0) a0 (if (= j 1) a1 (if (= j 2) a2 (if (= j 3) a3 a4)))))
        (setq j1 (+ j 1))
        (setq y (if (= j1 0) a0 (if (= j1 1) a1 (if (= j1 2) a2 (if (= j1 3) a3 a4)))))
        (if (> x y)
          (progn
            (if (= j 0) (setq a0 y)
              (if (= j 1) (setq a1 y)
                (if (= j 2) (setq a2 y)
                  (if (= j 3) (setq a3 y)
                    (setq a4 y)))))
            (if (= j1 0) (setq a0 x)
              (if (= j1 1) (setq a1 x)
                (if (= j1 2) (setq a2 x)
                  (if (= j1 3) (setq a3 x)
                    (setq a4 x)))))
          )
        )
        (setq j (+ j 1))
      )
      (setq i (+ i 1))
    )

    (setq k 0)
    (while (< k n)
      (setq v (if (= k 0) a0 (if (= k 1) a1 (if (= k 2) a2 (if (= k 3) a3 a4)))))
      (print v)
      (if (< (+ k 1) n) (out 32))
      (setq k (+ k 1))
    )
    (out 10)